# Generated by Django 5.2.9 on 2025-12-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('lote', models.CharField(help_text='Número do lote de fabricação', max_length=20)),
                ('quantidade', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=5, help_text='Quantidade mínima para alerta')),
                ('data_validade', models.DateField()),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
